package com.mycompany.jpademo.backend.security.filter;

import com.mycompany.jpademo.backend.entity.User;
import com.mycompany.jpademo.backend.enums.RoleName;
import com.mycompany.jpademo.backend.security.userdetails.CustomUserDetails;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.List;

/**
 * Forces any non-PATIENT account that has never changed its password
 * (lastChangePassTime == null — meaning it's still using the random
 * password auto-generated by an admin at creation time) to change it
 * before accessing anything else.
 */
@Component
public class ForcePasswordChangeFilter extends OncePerRequestFilter {

    private static final List<String> ALLOWED_PATHS = List.of(
            "/change-password",
            "/auth/logout",
            "/css/", "/js/", "/images/", "/img/", "/fonts/", "/webjars/"
    );

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
                                    FilterChain filterChain) throws ServletException, IOException {

        String uri = request.getRequestURI();
        if (ALLOWED_PATHS.stream().anyMatch(uri::startsWith)) {
            filterChain.doFilter(request, response);
            return;
        }

        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.isAuthenticated()
                && auth.getPrincipal() instanceof CustomUserDetails userDetails) {

            User user = userDetails.getUser();
            boolean isInternalAccount = user.getRole().getRoleName() != RoleName.PATIENT;
            boolean neverChangedPassword = user.getLastChangePassTime() == null;

            if (isInternalAccount && neverChangedPassword) {
                response.sendRedirect(request.getContextPath() + "/change-password");
                return;
            }
        }

        filterChain.doFilter(request, response);
    }
}